### ISSUE TITLE
"Outbound" is not a descriptive label in the integration dropdown

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-national-renewable-energy-lab#10]
Please change this to "Append Utility Info"
![leadconduit flows alex j s test flow edit 2016-02-05 15-58-44](https://cloud.githubusercontent.com/assets/140158/12860312/5f1ac3f2-cc21-11e5-9e87-c5bb262d077e.png)

**Comment by ros3bud** [comment]
Updated in 0.0.6
