### ISSUE TITLE
Weird drop-down behavior

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-national-renewable-energy-lab#12]
When adding the NREL integration, the selected item in the dropdown is blank instead of "Append Utility Info". When selecting the drop down to see if there's a different option, then choosing "Select Integration", the initial blank option disappears. Very confusing. 

![screencast 2016-02-11 12-33-45](https://cloud.githubusercontent.com/assets/140158/12986257/ded953d0-d0bb-11e5-9440-a928ebbdb80c.gif)

This might be related to issue #10 which was just fix.

**Comment by cgrayson** [comment]
Fixed in version `0.0.7`.
