### ISSUE TITLE
Only require postal_code

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-national-renewable-energy-lab#4]
NREL returns an error when only city and state are present. It will look like this: 

{
  "inputs": {
    "address": "undefined austin TX undefined"
  },
  "errors": [
    "Unable to geocode address: undefined austin TX undefined"
  ],
  "warnings": [],
  "version": "3.1.0",
  "metadata": {
    "sources": [
      "Ventyx Research (2012)"
    ]
  },
  "outputs": {}
}

This is strange because previous tests of mine did not get this result, but I think moving forward this should be accounted for. Further tests show that so long as postal_code is present, we get a result back - even with no address.

**Comment by ros3bud** [comment]
Resolved in 0.0.4

**Comment by alexkwolfe** [comment]
This failure might have been caused by passing undefined for the postal code. I find it hard to believe they couldn't geocode "Austin TX". 

It looks like you're also passing undefined for the street. Not sure if that's a problem. 

You might consider a safer routine for building the address.

**Comment by ros3bud** [comment]
resolved in 0.0.5
